robot_base_frame: base_link

transform_tolerance: 0.5

robot_radius: 0.30
inflater:
  inflation_radius: 0.50

obstacles:
  observation_sources: urg_cloud
  enabled: true
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  combination_method: 1

  urg_cloud:
    data_type: PointCloud2
    topic: urg_cloud
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: 0.0
    max_obstacle_height: 0.3
